# __Indexing__

## __Agenda__
In this lesson, we will explore the following concepts through examples:

- NumPy Array Indexing
  * Access Elements in the 1D NumPy Array
  * Access Elements in the 2D NumPy Array
  * Access Elements in 3D NumPy Array
  * Negative Indexing

## __1. NumPy Array Indexing__ ##
NumPy indexing lets you access an array element with an index value, starting from 0.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/4_Indexing/Image_1.png)

In [ ]:
# Creating 1D, 2D, and 3D NumPy arrays
import numpy as np
array_1d = np.array([1, 2, 3, 4, 5, 6])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

The above code creates 1D, 2D, and 3D NumPy arrays with specified elements, providing structured data representations for different dimensions.

### __1.1 Access Elements in the 1D NumPy Array__ ###

In [ ]:
# Print the value at index 3 of the 1D NumPy array
print(array_1d[3])

4


The above code prints the value located at index 3 of a one-dimensional NumPy array.

In [ ]:
# Print the sum of the values at indexes 0 and 1 in the 1D NumPy array
print(array_1d[1] + array_1d[0])

3


The above code calculates the sum of the values at the first and second indexes of a one-dimensional NumPy array.

### __1.2 Access Elements in the 2D NumPy Array__
Consider a 2D array as a table, with dimensions representing rows and indexes representing columns.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/4_Indexing/Image_2.png)

In [ ]:
# Printing the third element in the first row of the 2D array
print('Third element in the first row: ', array_2d[0, 2])

Third element in the first row:  3


The above code prints the value located in the first row and third column of a two-dimensional array.

In [ ]:
# Printing the second element in the second row of the 2D array
print('Second element in the second row: ', array_2d[1, 1])

Second element in the second row:  5


The above code prints the value located in the second row and second column of a two-dimensional array.

In [ ]:
# Print the 3D NumPy array
print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


The above code prints a 3D NumPy array. The output displays the array's elements organized in a cube-like structure, representing data arranged across three dimensions.

### __1.3 Access Elements in 3D NumPy Array__ ###
- [x, y, z] corresponds to the xth element, yth row, and zth column.

In [ ]:
# Print the first element of the first row of the second 2D array within the 3D array
print(array_3d[1, 0, 0])

7


The above code prints the value located in the first row and first column of the first matrix within the second set of matrices.

### __1.4 Negative Indexing__

- Negative indices count backward from the end of an array.
- In a negative indexing system, the last element will be the first element with an index of -1, the second last element with an index of -2, and so on.

In [ ]:
# Printing the fourth element from the end of the 1D array using negative indexing
print(array_1d[-3])

4


The above code prints the fourth element from the end of a 1D array. Negative indexing counts elements from the end.

In [ ]:
# Printing the last element in the second row of the 2D array using negative indexing
print(array_2d[1, -1])

6


The above code prints the last element in the second row of a 2D array.

In [ ]:
# Printing the last element in the last row of the last 2D array within the 3D array using negative indexing
print(array_3d[1, 1, -1])

12


The above code prints the last element in the last row of the last 2D array within the 3D array using negative indexing.

## __Assisted Practice__

### __Problem Statement:__

1. Create a one-dimensional NumPy array containing at least ten elements
2. Create a 2D NumPy array with a minimum of 3 rows and 4 columns
3. Create a 3D NumPy array with at least 2 matrices, each containing 2 rows and 3 columns
4. Access elements in NumPy arrays and utilize indexing and slicing techniques for efficient data retrieval
5. Access and print various elements from 1D, 2D, and 3D arrays using positive indexing
6. Perform and print some basic arithmetic operations (like addition or  subtraction) using elements accessed from 1D, 2D, and 3D arrays
7. Access and print elements using negative indices in all three arrays

In [1]:
import numpy as np

# Create a one-dimensional NumPy array containing at least ten elements
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create a 2D NumPy array with a minimum of 3 rows and 4 columns
array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

# Create a 3D NumPy array with at least 2 matrices, each containing 2 rows and 3 columns
array_3d = np.array([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]]])

In [2]:
# Access elements in NumPy arrays using positive indexing
print("Accessing elements using positive indexing:")
print("1D array:", array_1d[3])  # Accessing 4th element
print("2D array:", array_2d[1, 2])  # Accessing element at row 1, column 2
print("3D array:", array_3d[1, 0, 2])  # Ac

Accessing elements using positive indexing:
1D array: 4
2D array: 7
3D array: 9


In [3]:
array_3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [4]:
print("\nPerforming basic arithmetic operations:")
print("Sum of 1D array:", np.sum(array_1d))
print("Sum of 2D array:", np.sum(array_2d))
print("Sum of 3D array:", np.sum(array_3d))


Performing basic arithmetic operations:
Sum of 1D array: 55
Sum of 2D array: 78
Sum of 3D array: 78


In [5]:
# Access and print elements using negative indices in all three arrays
print("\nAccessing elements using negative indexing:")
print("Last element of 1D array:", array_1d[-1])
print("Second last element of 2D array:", array_2d[-2, -2])
print("Last element of 3D array:", array_3d[-1, -1, -1])


Accessing elements using negative indexing:
Last element of 1D array: 10
Second last element of 2D array: 7
Last element of 3D array: 12


In [6]:
#np.subraction
import numpy as np

# Create sample arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

# Perform subtraction using np.subtract()
result = np.subtract(array1, array2)

# Print result
print("Subtraction using np.subtract():", result)

Subtraction using np.subtract(): [-4 -2  0  2  4]


In [7]:
##
# Creating a 5 x 3 array of ones
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
# Notice that, by default, numpy creates data type = float64
# Can provide dtype explicitly using dtype
np.ones((5, 3), dtype = np.int)

C:\Users\DK\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  This is separate from the ipykernel package so we can avoid doing imports until


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [9]:
# Creating array of zeros
np.zeros(4, dtype = np.int)

C:\Users\DK\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


array([0, 0, 0, 0])

In [10]:
# Creating array of zeros
np.zeros((4,2), dtype = np.int)

C:\Users\DK\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [11]:
# Array of random numbers
np.random.random([3, 4])

array([[0.47078355, 0.55354743, 0.85234382, 0.29849523],
       [0.333758  , 0.20914493, 0.17578233, 0.02764417],
       [0.59510599, 0.32324541, 0.85630713, 0.1462356 ]])

In [12]:
np.random.randint(5, size=(2,4))

array([[4, 4, 2, 0],
       [3, 1, 0, 0]])

In [13]:
# np.arange()
# np.arange() is the numpy equivalent of range()
# Notice that 10 is included, 100 is not, as in standard python lists

# From 10 to 100 with a step of 5
numbers = np.arange(10, 100, 5)
print(numbers)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [14]:
# Creating a 4 x 3 array of 7s using np.full()
# The default data type here is int only
np.full((4,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [15]:
# Initialising a random 1000 x 300 array
rand_array = np.random.random((1000, 300))

# Print the second row
print(rand_array[1, ])

[0.20058084 0.5633177  0.6108342  0.67111917 0.90946314 0.91914947
 0.69057072 0.32849375 0.45362516 0.98446739 0.79648917 0.51241153
 0.04459819 0.852227   0.63011767 0.4899216  0.67219902 0.6377453
 0.8207507  0.94441099 0.93234191 0.70667098 0.78875348 0.22338034
 0.14953424 0.85738233 0.15772494 0.59564508 0.7185993  0.37487607
 0.1166272  0.9771958  0.1528019  0.60274746 0.06243778 0.15196465
 0.47667546 0.72878437 0.06271495 0.07996656 0.55474942 0.18582986
 0.1219744  0.7919007  0.42655399 0.50005915 0.40311042 0.37047646
 0.04484432 0.47690947 0.46976182 0.10138242 0.32466835 0.61352914
 0.79643439 0.19342668 0.62762774 0.53739115 0.76757297 0.39380148
 0.75977963 0.13469212 0.9658983  0.53911757 0.21851249 0.91333794
 0.25805059 0.48910584 0.95662786 0.01735759 0.94342643 0.45950653
 0.8727735  0.60289475 0.72387214 0.38274303 0.97249996 0.8579334
 0.88493471 0.718325   0.18683171 0.90188095 0.72232693 0.00584805
 0.22980042 0.30406018 0.62434393 0.72899628 0.52639396 0.462469

In [17]:
# Inspecting shape, dtype, ndim and itemsize
print("Shape: {}".format(rand_array.shape))
print("dtype: {}".format(rand_array.dtype))
print("Dimensions: {}".format(rand_array.ndim))
print("Size: {}".format(rand_array.size))

Shape: (1000, 300)
dtype: float64
Dimensions: 2
Item size: 8
Size: 300000


In [20]:
print("Data: {}".format(rand_array.data))


Data: <memory at 0x0000022016913828>


In [21]:
# Creating a 3-D array
# reshape() simply reshapes a 1-D array 
array_3d = np.arange(24).reshape(2, 3, 4)
print(array_3d)
print(array_3d.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [22]:
list_1 = [3, 6, 7, 5]
list_2 = [4, 5, 1, 7]

# the list way to do it: map a function to the two lists
product_list = list(map(lambda x, y: x*y, list_1, list_2))
print(product_list)

[12, 30, 7, 35]


In [23]:
# The numpy array way to do it: simply multiply the two arrays
array_1 = np.array(list_1)
array_2 = np.array(list_2)

array_3 = array_1*array_2
print(array_3)
print(type(array_3))

[12 30  7 35]
<class 'numpy.ndarray'>
